/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;


import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BooksAvalibilityForm extends javax.swing.JFrame {

    /**
     * Creates new form BooksAvalibilityForm
     */
    public ConnectDb dbconnect = new ConnectDb();

    public BooksAvalibilityForm() {
        initComponents();
       this.setLocationRelativeTo(null);
       
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jTextField1 = new javax.swing.JTextField();
        Avalibility_choosen_dropdown = new javax.swing.JComboBox<>();
        Avalibility_panel_0 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        goback = new javax.swing.JButton();
        Avalibility_panel_1 = new javax.swing.JPanel();
        Avalibility_criteria_fieldname = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Okay_button = new javax.swing.JButton();
        Avalibility_panel_3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Avalibility_outputtable = new javax.swing.JTable();
        Avalibility_panel_2 = new javax.swing.JPanel();
        Avalibility_choosen_fieldname = new javax.swing.JLabel();
        Search_button = new javax.swing.JButton();
        CriteriaTextField = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        jTextField1.setText("jTextField1");

        Avalibility_choosen_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Avalibility_choosen_dropdownActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Avalibility_panel_0.setBackground(java.awt.Color.white);

        title.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        title.setText("       Books Availability");

        goback.setBackground(java.awt.Color.black);
        goback.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        goback.setForeground(java.awt.Color.white);
        goback.setText("Go Back");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        Avalibility_panel_1.setBackground(java.awt.Color.white);
        Avalibility_panel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Avalibility_panel_1.setForeground(java.awt.Color.white);

        Avalibility_criteria_fieldname.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Avalibility_criteria_fieldname.setText("Choose a criteria");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "genre", "level", "publisher", "author" }));

        Okay_button.setBackground(java.awt.Color.black);
        Okay_button.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Okay_button.setForeground(java.awt.Color.white);
        Okay_button.setText("Okay");
        Okay_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Okay_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Avalibility_panel_1Layout = new javax.swing.GroupLayout(Avalibility_panel_1);
        Avalibility_panel_1.setLayout(Avalibility_panel_1Layout);
        Avalibility_panel_1Layout.setHorizontalGroup(
            Avalibility_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Avalibility_panel_1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(Avalibility_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_1Layout.createSequentialGroup()
                        .addComponent(Avalibility_criteria_fieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_1Layout.createSequentialGroup()
                        .addComponent(Okay_button)
                        .addGap(129, 129, 129))))
        );
        Avalibility_panel_1Layout.setVerticalGroup(
            Avalibility_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Avalibility_panel_1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Avalibility_criteria_fieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Okay_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Avalibility_panel_3.setBackground(java.awt.Color.white);
        Avalibility_panel_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Avalibility_outputtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book title", "Book Level", "Book Genre ", "Book publisher", " Book Author"
            }
        ));
        jScrollPane1.setViewportView(Avalibility_outputtable);
        if (Avalibility_outputtable.getColumnModel().getColumnCount() > 0) {
            Avalibility_outputtable.getColumnModel().getColumn(0).setHeaderValue("Book ID");
            Avalibility_outputtable.getColumnModel().getColumn(1).setHeaderValue("Book title");
            Avalibility_outputtable.getColumnModel().getColumn(2).setHeaderValue("Book Level");
            Avalibility_outputtable.getColumnModel().getColumn(3).setHeaderValue("Book Genre ");
            Avalibility_outputtable.getColumnModel().getColumn(4).setHeaderValue("Book publisher");
            Avalibility_outputtable.getColumnModel().getColumn(5).setHeaderValue(" Book Author");
        }

        javax.swing.GroupLayout Avalibility_panel_3Layout = new javax.swing.GroupLayout(Avalibility_panel_3);
        Avalibility_panel_3.setLayout(Avalibility_panel_3Layout);
        Avalibility_panel_3Layout.setHorizontalGroup(
            Avalibility_panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Avalibility_panel_3Layout.setVerticalGroup(
            Avalibility_panel_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        Avalibility_panel_2.setBackground(java.awt.Color.white);
        Avalibility_panel_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Avalibility_choosen_fieldname.setBackground(java.awt.Color.black);
        Avalibility_choosen_fieldname.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N

        Search_button.setBackground(java.awt.Color.black);
        Search_button.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Search_button.setForeground(java.awt.Color.white);
        Search_button.setText("Search");
        Search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_buttonActionPerformed(evt);
            }
        });

        CriteriaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriteriaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Avalibility_panel_2Layout = new javax.swing.GroupLayout(Avalibility_panel_2);
        Avalibility_panel_2.setLayout(Avalibility_panel_2Layout);
        Avalibility_panel_2Layout.setHorizontalGroup(
            Avalibility_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Avalibility_panel_2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Avalibility_choosen_fieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(CriteriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Avalibility_panel_2Layout.setVerticalGroup(
            Avalibility_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(Avalibility_choosen_fieldname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CriteriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout Avalibility_panel_0Layout = new javax.swing.GroupLayout(Avalibility_panel_0);
        Avalibility_panel_0.setLayout(Avalibility_panel_0Layout);
        Avalibility_panel_0Layout.setHorizontalGroup(
            Avalibility_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Avalibility_panel_0Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(goback)
                .addGap(83, 83, 83)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Avalibility_panel_0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Avalibility_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Avalibility_panel_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Avalibility_panel_0Layout.createSequentialGroup()
                        .addComponent(Avalibility_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(Avalibility_panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        Avalibility_panel_0Layout.setVerticalGroup(
            Avalibility_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Avalibility_panel_0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Avalibility_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Avalibility_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Avalibility_panel_0Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Avalibility_panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Avalibility_panel_0Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Avalibility_panel_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Avalibility_panel_3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Avalibility_panel_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Avalibility_panel_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        // TODO add your handling code here:
        Dashboardform Dashform = new Dashboardform();
            Dashform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_gobackActionPerformed

    private void Search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_buttonActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("genre")){
            DefaultTableModel model = (DefaultTableModel) Avalibility_outputtable.getModel();
            model.setRowCount(0);

             try {
            Statement st = dbconnect.librarycon.createStatement();
            String firstSql = "Select * from book where issued = 'N' and  genre ='" +CriteriaTextField.getText()+"'";
            System.out.println(firstSql);
            ResultSet rs = st.executeQuery(firstSql);
	while (rs.next()) {
		String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String level = String.valueOf(rs.getInt("level"));
                String genre = rs.getString("genre");
                String publisher = rs.getString("publisher");
                String author = rs.getString("author");

                String tbData[] = {id,name,level,genre,publisher,author};
                DefaultTableModel tblmodle = (DefaultTableModel)Avalibility_outputtable.getModel();
                
                tblmodle.addRow(tbData);
		}
		} catch (Exception e) {
		}
        }else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("level")){
            DefaultTableModel model = (DefaultTableModel) Avalibility_outputtable.getModel();
            model.setRowCount(0);

             try {
            Statement st = dbconnect.librarycon.createStatement();
            String firstSql = "Select * from book where issued = 'N' and  level ='" +Integer.parseInt(CriteriaTextField.getText())+"'";
            System.out.println(firstSql);
            ResultSet rs = st.executeQuery(firstSql);
	while (rs.next()) {
		String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String level = String.valueOf(rs.getInt("level"));
                String genre = rs.getString("genre");
                String publisher = rs.getString("publisher");
                String author = rs.getString("author");

                String tbData[] = {id,name,level,genre,publisher,author};
                DefaultTableModel tblmodle = (DefaultTableModel)Avalibility_outputtable.getModel();
                
                tblmodle.addRow(tbData);
		}
		} catch (Exception e) {
		}
        }else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("publisher")){
            DefaultTableModel model = (DefaultTableModel) Avalibility_outputtable.getModel();
            model.setRowCount(0);
             try {
            Statement st = dbconnect.librarycon.createStatement();
            String firstSql = "Select * from book where issued = 'N' and  publisher ='" +CriteriaTextField.getText()+"'";
            ResultSet rs = st.executeQuery(firstSql);
	while (rs.next()) {
		String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String level = String.valueOf(rs.getInt("level"));
                String genre = rs.getString("genre");
                String publisher = rs.getString("publisher");
                String author = rs.getString("author");

                String tbData[] = {id,name,level,genre,publisher,author};
                DefaultTableModel tblmodle = (DefaultTableModel)Avalibility_outputtable.getModel();
                
                tblmodle.addRow(tbData);
		}
		} catch (Exception e) {
		}
        }else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("author")){
            DefaultTableModel model = (DefaultTableModel) Avalibility_outputtable.getModel();
            model.setRowCount(0);
             try {
            Statement st = dbconnect.librarycon.createStatement();
            String firstSql = "Select * from book where issued = 'N' and  author ='" +CriteriaTextField.getText()+"'";
            ResultSet rs = st.executeQuery(firstSql);
	while (rs.next()) {
		String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String level = String.valueOf(rs.getInt("level"));
                String genre = rs.getString("genre");
                String publisher = rs.getString("publisher");
                String author = rs.getString("author");

                String tbData[] = {id,name,level,genre,publisher,author};
                DefaultTableModel tblmodle = (DefaultTableModel)Avalibility_outputtable.getModel();
                
                tblmodle.addRow(tbData);
		}
		} catch (Exception e) {
		}
        }
        
    }//GEN-LAST:event_Search_buttonActionPerformed

    private void Okay_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Okay_buttonActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("genre")){
            Avalibility_choosen_fieldname.setText("genre");
            
        }else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("level")){
            Avalibility_choosen_fieldname.setText("Level");
           
        }else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("publisher")){
            Avalibility_choosen_fieldname.setText("Publisher");
           
        }else if(jComboBox1.getSelectedItem().toString().equalsIgnoreCase("author")){
            Avalibility_choosen_fieldname.setText("author");
            
        }

    }//GEN-LAST:event_Okay_buttonActionPerformed

    private void Avalibility_choosen_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Avalibility_choosen_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Avalibility_choosen_dropdownActionPerformed

    private void CriteriaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriteriaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CriteriaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BooksAvalibilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BooksAvalibilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BooksAvalibilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BooksAvalibilityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BooksAvalibilityForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Avalibility_choosen_dropdown;
    private javax.swing.JLabel Avalibility_choosen_fieldname;
    private javax.swing.JLabel Avalibility_criteria_fieldname;
    private javax.swing.JTable Avalibility_outputtable;
    private javax.swing.JPanel Avalibility_panel_0;
    private javax.swing.JPanel Avalibility_panel_1;
    private javax.swing.JPanel Avalibility_panel_2;
    private javax.swing.JPanel Avalibility_panel_3;
    private javax.swing.JTextField CriteriaTextField;
    private javax.swing.JButton Okay_button;
    private javax.swing.JButton Search_button;
    private javax.swing.JButton goback;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
