/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;


public class Dashboardform extends javax.swing.JFrame {

    /**
     * Creates new form Dashboardform
     */
    
    public Dashboardform() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboard_jpanel_0 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        title_1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        Books_button = new javax.swing.JButton();
        issue_return_button = new javax.swing.JButton();
        avalibility_button = new javax.swing.JButton();
        student_button = new javax.swing.JButton();
        report_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboard_jpanel_0.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        title.setText("Welcome to digital library managmant");

        title_1.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        title_1.setText("          Main Menu");
        title_1.setToolTipText("");

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setForeground(java.awt.Color.white);
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        Books_button.setBackground(java.awt.Color.black);
        Books_button.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        Books_button.setForeground(java.awt.Color.white);
        Books_button.setText("Books");
        Books_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Books_buttonActionPerformed(evt);
            }
        });

        issue_return_button.setBackground(java.awt.Color.black);
        issue_return_button.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        issue_return_button.setForeground(java.awt.Color.white);
        issue_return_button.setText("Books Issue/Return");
        issue_return_button.setActionCommand("Books issue/ return");
        issue_return_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue_return_buttonActionPerformed(evt);
            }
        });

        avalibility_button.setBackground(java.awt.Color.black);
        avalibility_button.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        avalibility_button.setForeground(java.awt.Color.white);
        avalibility_button.setText("Books Availability");
        avalibility_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avalibility_buttonActionPerformed(evt);
            }
        });

        student_button.setBackground(java.awt.Color.black);
        student_button.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        student_button.setForeground(java.awt.Color.white);
        student_button.setText("Student Records");
        student_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_buttonActionPerformed(evt);
            }
        });

        report_button.setBackground(java.awt.Color.black);
        report_button.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        report_button.setForeground(java.awt.Color.white);
        report_button.setText("Progress Report");
        report_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dashboard_jpanel_0Layout = new javax.swing.GroupLayout(dashboard_jpanel_0);
        dashboard_jpanel_0.setLayout(dashboard_jpanel_0Layout);
        dashboard_jpanel_0Layout.setHorizontalGroup(
            dashboard_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_jpanel_0Layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(dashboard_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboard_jpanel_0Layout.createSequentialGroup()
                        .addComponent(title_1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboard_jpanel_0Layout.createSequentialGroup()
                        .addGroup(dashboard_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dashboard_jpanel_0Layout.createSequentialGroup()
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(dashboard_jpanel_0Layout.createSequentialGroup()
                                .addGroup(dashboard_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(issue_return_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Books_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(avalibility_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(student_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(report_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)))
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        dashboard_jpanel_0Layout.setVerticalGroup(
            dashboard_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboard_jpanel_0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboard_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title_1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Books_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(issue_return_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(avalibility_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(student_button, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(report_button, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard_jpanel_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboard_jpanel_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Books_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Books_buttonActionPerformed
        // TODO add your handling code here:
        Booksform bookform = new Booksform();
            bookform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_Books_buttonActionPerformed

    private void issue_return_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue_return_buttonActionPerformed
        // TODO add your handling code here
        Booksinventory bookinventoryform = new Booksinventory();
            bookinventoryform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_issue_return_buttonActionPerformed

    private void avalibility_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avalibility_buttonActionPerformed
        // TODO add your handling code here:
        BooksAvalibilityForm bookavalibilityform = new BooksAvalibilityForm();
            bookavalibilityform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_avalibility_buttonActionPerformed

    private void student_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_buttonActionPerformed
        // TODO add your handling code here:
        Studentform studentform = new Studentform();
            studentform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_student_buttonActionPerformed

    private void report_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_buttonActionPerformed
        // TODO add your handling code here:
         Progressreport progressreportform = new Progressreport();
            progressreportform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_report_buttonActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Loginform loginform = new Loginform();
            loginform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_logoutActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboardform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboardform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboardform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboardform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboardform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Books_button;
    private javax.swing.JButton avalibility_button;
    private javax.swing.JPanel dashboard_jpanel_0;
    private javax.swing.JButton issue_return_button;
    private javax.swing.JButton logout;
    private javax.swing.JButton report_button;
    private javax.swing.JButton student_button;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title_1;
    // End of variables declaration//GEN-END:variables
}
