/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;


import java.awt.event.ActionEvent;
import java.lang.reflect.InvocationTargetException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;
import java.util.Map;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VAIBHAV
 */
public class Progressreport extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    Statement st = null;

    ResultSet rs = null;
	
    Map<Integer, String> graph = new HashMap<Integer, String>();

    public ConnectDb dbconnect = new ConnectDb();
	
	JScrollPane jScrollPanel = new JScrollPane();
        	private static final String ISO_8601_DATE_FORMAT_WITH_MILLIS = "yyyy-MM-dd";


	static final Logger logger = Logger.getLogger(Progressreport.class.getName());
	
    public Progressreport() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            Statement st = dbconnect.librarycon.createStatement();
	String firstSql = "Select id from student";
	rs = st.executeQuery(firstSql);
	while (rs.next()) {
		report_id_dropdown.addItem(rs.getString(1));
             
		}
		rs.close();
		} catch (Exception e) {
		}

        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        report_panel_0 = new javax.swing.JPanel();
        goback = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        report_id_fieldname = new javax.swing.JLabel();
        report_id_dropdown = new javax.swing.JComboBox<>();
        report_start_date_fieldname = new javax.swing.JLabel();
        report_end_date_fieldname = new javax.swing.JLabel();
        report_search = new javax.swing.JButton();
        report_panel_1 = new javax.swing.JPanel();
        title_1 = new javax.swing.JLabel();
        Reportmainbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        report_outputtable = new javax.swing.JTable();
        report_graph = new javax.swing.JButton();
        report_start_date_datechooser = new com.toedter.calendar.JDateChooser();
        report_end_date_datechooser = new com.toedter.calendar.JDateChooser();
        report_name_fieldtext = new javax.swing.JTextField();
        report_name_fieldname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        report_panel_0.setBackground(java.awt.Color.white);

        goback.setBackground(java.awt.Color.black);
        goback.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        goback.setForeground(java.awt.Color.white);
        goback.setText("Go Back");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        title.setText("Progress Report");

        report_id_fieldname.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        report_id_fieldname.setText("Choose the student ID");

        report_id_dropdown.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        report_id_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_id_dropdownActionPerformed(evt);
            }
        });

        report_start_date_fieldname.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        report_start_date_fieldname.setText("Start Date");

        report_end_date_fieldname.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        report_end_date_fieldname.setText("End Date");

        report_search.setBackground(java.awt.Color.black);
        report_search.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        report_search.setForeground(java.awt.Color.white);
        report_search.setText("Search");
        report_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_searchActionPerformed(evt);
            }
        });

        report_panel_1.setBackground(java.awt.Color.white);
        report_panel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        title_1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        title_1.setText("Books Read Table and Graph");

        Reportmainbutton.setBackground(java.awt.Color.black);
        Reportmainbutton.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Reportmainbutton.setForeground(java.awt.Color.white);
        Reportmainbutton.setText("Download Report");
        Reportmainbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportmainbuttonActionPerformed(evt);
            }
        });

        report_outputtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book name", "Date of issue", "Date of return"
            }
        ));
        jScrollPane1.setViewportView(report_outputtable);

        report_graph.setBackground(java.awt.Color.black);
        report_graph.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        report_graph.setForeground(java.awt.Color.white);
        report_graph.setText("Graph");
        report_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                report_graphActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout report_panel_1Layout = new javax.swing.GroupLayout(report_panel_1);
        report_panel_1.setLayout(report_panel_1Layout);
        report_panel_1Layout.setHorizontalGroup(
            report_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panel_1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panel_1Layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(report_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panel_1Layout.createSequentialGroup()
                        .addComponent(title_1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(report_graph, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panel_1Layout.createSequentialGroup()
                        .addComponent(Reportmainbutton)
                        .addGap(42, 42, 42))))
        );
        report_panel_1Layout.setVerticalGroup(
            report_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(report_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(report_graph))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reportmainbutton)
                .addGap(201, 201, 201))
        );

        report_name_fieldname.setText("Student Name");

        javax.swing.GroupLayout report_panel_0Layout = new javax.swing.GroupLayout(report_panel_0);
        report_panel_0.setLayout(report_panel_0Layout);
        report_panel_0Layout.setHorizontalGroup(
            report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panel_0Layout.createSequentialGroup()
                .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(report_panel_0Layout.createSequentialGroup()
                            .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(report_panel_0Layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(report_id_fieldname))
                                .addGroup(report_panel_0Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(report_name_fieldtext, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(report_id_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(123, 123, 123)
                            .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(report_start_date_fieldname)
                                .addComponent(report_end_date_fieldname))
                            .addGap(41, 41, 41)
                            .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(report_start_date_datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                .addComponent(report_end_date_datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(report_panel_0Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(report_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(report_panel_0Layout.createSequentialGroup()
                                    .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(145, 145, 145)
                                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, report_panel_0Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(report_search, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)))
                    .addGroup(report_panel_0Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(report_name_fieldname)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        report_panel_0Layout.setVerticalGroup(
            report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(report_panel_0Layout.createSequentialGroup()
                .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(report_panel_0Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(goback))
                    .addGroup(report_panel_0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(report_panel_0Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(report_id_fieldname))
                    .addGroup(report_panel_0Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(report_start_date_datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(report_start_date_fieldname))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(report_panel_0Layout.createSequentialGroup()
                        .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(report_end_date_fieldname)
                            .addComponent(report_id_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(report_name_fieldname)
                        .addGap(1, 1, 1)
                        .addGroup(report_panel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(report_search)
                            .addComponent(report_name_fieldtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(report_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(report_end_date_datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(report_panel_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(report_panel_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        // TODO add your handling code here:
        Dashboardform Dashform = new Dashboardform();
            Dashform.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_gobackActionPerformed

    private void report_id_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_id_dropdownActionPerformed
        // TODO add your handling code here:
        try{
         Statement st = dbconnect.librarycon.createStatement();
            String firstSql = "Select name from student where id = '"+report_id_dropdown.getSelectedItem().toString()+"'";
            ResultSet rs = st.executeQuery(firstSql);
            while(rs.next()){
                report_name_fieldtext.setText(rs.getString("name"));

            }
                }
    catch(Exception e){
      e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);   
    }

    }//GEN-LAST:event_report_id_dropdownActionPerformed

    private void report_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_searchActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) report_outputtable.getModel();
            model.setRowCount(0);
              java.sql.Date sqldate = new java.sql.Date(report_start_date_datechooser.getDate().getTime());
           java.sql.Date sqldate1 = new java.sql.Date(report_end_date_datechooser.getDate().getTime());
                   SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                       
            try{    
                    st = dbconnect.librarycon.createStatement();
                    String sql = "select title,datei,dater from inventory  " + "where  datei " + "between '" + sqldate
						+ "' and '" + sqldate1 + "' and ids ='" + report_id_dropdown.getModel().getSelectedItem() + "'";
                    ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {

                String title = rs.getString("title");
                String datei = rs.getString("datei");
                System.out.println(datei);
                String dater = rs.getString("dater");

                String tbData[] = {title,datei,dater};
                DefaultTableModel tblmodle = (DefaultTableModel)report_outputtable.getModel();
                
                tblmodle.addRow(tbData);
                
		}

                
				}
        catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
			}

            
            
            
       
        
    }//GEN-LAST:event_report_searchActionPerformed

    
    private void ReportmainbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportmainbuttonActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyy");
 
        try{
             String sql = "Delete from report";
		PreparedStatement ps = dbconnect.librarycon.prepareStatement(sql);
		ps.execute();
        }
         catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
			}
        DefaultTableModel tblModel = (DefaultTableModel) report_outputtable.getModel();
         try{    
             for(int i=0;i<tblModel.getRowCount();i++){
                 String title = tblModel.getValueAt(i, 0).toString();
                 String datei = String.valueOf(tblModel.getValueAt(i, 1));
                 String dater = String.valueOf(tblModel.getValueAt(i, 2)); 
                 
                  String sql = "Insert into report (title,datei,dater) values(?,?,?) ";
                  PreparedStatement ps = dbconnect.librarycon.prepareStatement(sql);
                  ps.setString(1, title);
                  ps.setString(2, datei);
                  ps.setString(3, dater);
                  ps.execute();
             }}
        catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
			}
         try{

        String Report = "C:\\Users\\VAIBHAV\\Documents\\NetBeansProjects\\library_mangament_software\\src\\main\\java\\My_Forms\\ProgressReport.jrxml";
         JasperReport jr = JasperCompileManager.compileReport(Report);
         JasperPrint jp = JasperFillManager.fillReport(jr, null,dbconnect.librarycon);
         JasperViewer.viewReport(jp);
        }
        catch(Exception e){
         e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
        }
       
        
         


    }//GEN-LAST:event_ReportmainbuttonActionPerformed

    
    private void report_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_report_graphActionPerformed
        // TODO add your handling code here:
				try {
					reportGraph(evt);
				} catch (InvocationTargetException | InterruptedException e) {
				}		
    }//GEN-LAST:event_report_graphActionPerformed

    protected void reportGraph(ActionEvent evt) throws InvocationTargetException, InterruptedException {
		java.sql.Date sqldate = new java.sql.Date(report_start_date_datechooser.getDate().getTime());
           java.sql.Date sqldate1 = new java.sql.Date(report_end_date_datechooser.getDate().getTime());
		String sql = "SELECT Count(datei), EXTRACT(month FROM datei)  FROM inventory " + "where  datei " + "between '" + sqldate
						+ "' and '" + sqldate1 + "' and ids ='" + report_id_dropdown.getModel().getSelectedItem() + "' Group by EXTRACT(month FROM datei)";
                System.out.println(sql);
		try {
			rs = st.executeQuery(sql);
			while (rs.next()) {
				switch (rs.getString(2)) {
				case "1":
					graph.put(rs.getInt(1), "JAN");
					break;
				case "2":
					graph.put(rs.getInt(1), "FEB");
					break;
				case "3":
					graph.put(rs.getInt(1), "MAR");
					break;
				case "4":
					graph.put(rs.getInt(1), "APR");
					break;
				case "5":
					graph.put(rs.getInt(1), "MAY");
					break;
				case "6":
					graph.put(rs.getInt(1), "JUNE");
					break;
				case "7":
					graph.put(rs.getInt(1), "JULY");
					break;
				case "8":
					graph.put(rs.getInt(1), "AUG");
					break;
				case "9":
					graph.put(rs.getInt(1), "SEP");
					break;
				case "10":
					graph.put(rs.getInt(1), "OCT");
					break;
				case "11":
					graph.put(rs.getInt(1), "NOV");
					break;
				case "12":
					graph.put(rs.getInt(1), "DEC");
					break;
				}
                                

			}
		} catch (SQLException e) {
                     e.printStackTrace();
                JOptionPane.showMessageDialog(null, e);
		}
                                    
			Chart example = new Chart(graph);
			example.setSize(900, 600);
			example.setLocationRelativeTo(null);
			example.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
			example.setVisible(true);

	}

	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Progressreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Progressreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Progressreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Progressreport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Progressreport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reportmainbutton;
    private javax.swing.JButton goback;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser report_end_date_datechooser;
    private javax.swing.JLabel report_end_date_fieldname;
    private javax.swing.JButton report_graph;
    private javax.swing.JComboBox<String> report_id_dropdown;
    private javax.swing.JLabel report_id_fieldname;
    private javax.swing.JLabel report_name_fieldname;
    private javax.swing.JTextField report_name_fieldtext;
    private javax.swing.JTable report_outputtable;
    private javax.swing.JPanel report_panel_0;
    private javax.swing.JPanel report_panel_1;
    private javax.swing.JButton report_search;
    private com.toedter.calendar.JDateChooser report_start_date_datechooser;
    private javax.swing.JLabel report_start_date_fieldname;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title_1;
    // End of variables declaration//GEN-END:variables
}
