/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VAIBHAV
 */

public class Studentform extends javax.swing.JFrame {

    /**
     * Creates new form Studentform
     */
    public ConnectDb dbconnect = new ConnectDb();
    
    
    
    public Studentform()  {
        initComponents();
        this.setLocationRelativeTo(null);            
        try {
            Statement st = dbconnect.librarycon.createStatement();
            String firstSql = "Select * from student order by id";
            ResultSet rs = st.executeQuery(firstSql);
	while (rs.next()) {
		String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String grade  = String.valueOf(rs.getInt("grade"));
                        
                String tbData[] = {id,name,grade};
                DefaultTableModel tblmodle = (DefaultTableModel)Output_table.getModel();
                
                tblmodle.addRow(tbData);
		}
		rs.close();
		} catch (Exception e) {
		}

        
        }
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        student_jpanel_0 = new javax.swing.JPanel();
        Goback = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        student_panel_1 = new javax.swing.JPanel();
        Student_add = new javax.swing.JButton();
        student_id_feildname = new javax.swing.JLabel();
        student_name_feildname = new javax.swing.JLabel();
        student_class_feildname = new javax.swing.JLabel();
        student_name_feildtext = new javax.swing.JTextField();
        student_class_feildtext = new javax.swing.JTextField();
        student_id_feildtext = new javax.swing.JTextField();
        Student_update = new javax.swing.JButton();
        Student_delete = new javax.swing.JButton();
        student_panel_2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Output_table = new javax.swing.JTable();
        refresh = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        student_jpanel_0.setBackground(java.awt.Color.white);

        Goback.setBackground(java.awt.Color.black);
        Goback.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Goback.setForeground(java.awt.Color.white);
        Goback.setText("Go Back");
        Goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GobackActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        title.setText("           Student Records");

        student_panel_1.setBackground(java.awt.Color.white);
        student_panel_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Student_add.setBackground(java.awt.Color.black);
        Student_add.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Student_add.setForeground(java.awt.Color.white);
        Student_add.setText("Add");
        Student_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_addActionPerformed(evt);
            }
        });

        student_id_feildname.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        student_id_feildname.setText("Student ID");

        student_name_feildname.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        student_name_feildname.setText("Student Name");

        student_class_feildname.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        student_class_feildname.setText("Student Class");

        student_name_feildtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_name_feildtextActionPerformed(evt);
            }
        });

        student_id_feildtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_id_feildtextActionPerformed(evt);
            }
        });

        Student_update.setBackground(java.awt.Color.black);
        Student_update.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Student_update.setForeground(java.awt.Color.white);
        Student_update.setText("Update");
        Student_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_updateActionPerformed(evt);
            }
        });

        Student_delete.setBackground(java.awt.Color.black);
        Student_delete.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Student_delete.setForeground(java.awt.Color.white);
        Student_delete.setText("Delete");
        Student_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout student_panel_1Layout = new javax.swing.GroupLayout(student_panel_1);
        student_panel_1.setLayout(student_panel_1Layout);
        student_panel_1Layout.setHorizontalGroup(
            student_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, student_panel_1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(student_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(student_name_feildtext)
                    .addComponent(student_class_feildtext)
                    .addComponent(student_id_feildtext, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(student_panel_1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(student_class_feildname))
                    .addGroup(student_panel_1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(student_id_feildname)))
                .addGap(229, 229, 229))
            .addGroup(student_panel_1Layout.createSequentialGroup()
                .addGroup(student_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(student_panel_1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(Student_add, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(Student_update, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(Student_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(student_panel_1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(student_name_feildname)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        student_panel_1Layout.setVerticalGroup(
            student_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, student_panel_1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(student_id_feildname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(student_id_feildtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(student_name_feildname, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(student_name_feildtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(student_class_feildname)
                .addGap(18, 18, 18)
                .addComponent(student_class_feildtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(student_panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Student_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        student_panel_2.setBackground(java.awt.Color.white);
        student_panel_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Output_table.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Output_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Student Class"
            }
        ));
        Output_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Output_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Output_table);

        refresh.setBackground(java.awt.Color.black);
        refresh.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        refresh.setForeground(java.awt.Color.white);
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout student_panel_2Layout = new javax.swing.GroupLayout(student_panel_2);
        student_panel_2.setLayout(student_panel_2Layout);
        student_panel_2Layout.setHorizontalGroup(
            student_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_panel_2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(student_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, student_panel_2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, student_panel_2Layout.createSequentialGroup()
                        .addComponent(refresh)
                        .addGap(41, 41, 41))))
        );
        student_panel_2Layout.setVerticalGroup(
            student_panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, student_panel_2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout student_jpanel_0Layout = new javax.swing.GroupLayout(student_jpanel_0);
        student_jpanel_0.setLayout(student_jpanel_0Layout);
        student_jpanel_0Layout.setHorizontalGroup(
            student_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_jpanel_0Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(student_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(student_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(student_jpanel_0Layout.createSequentialGroup()
                        .addComponent(Goback)
                        .addGap(78, 78, 78)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(student_panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        student_jpanel_0Layout.setVerticalGroup(
            student_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_jpanel_0Layout.createSequentialGroup()
                .addGroup(student_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Goback))
                .addGap(18, 18, 18)
                .addComponent(student_panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(student_panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_jpanel_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_jpanel_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GobackActionPerformed
        // TODO add your handling code here:
        Dashboardform Dashform = new Dashboardform();
            Dashform.setVisible(true);
            this.setVisible(false);
            
    }//GEN-LAST:event_GobackActionPerformed

    private void student_name_feildtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_name_feildtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_name_feildtextActionPerformed

    private void Student_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_addActionPerformed
        // TODO add your handling code here:
        if ( student_name_feildtext.getText().isEmpty() || student_class_feildtext.getText().isEmpty() || student_id_feildtext.getText().isEmpty() ){
            JOptionPane.showMessageDialog(new JFrame(), "Enter value in the feilds ", "Message" , JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                String sql =  "Insert into student" + "(id,name,grade)" + "values(?,?,?)";
		PreparedStatement ps = dbconnect.librarycon.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(student_id_feildtext.getText()));
                ps.setString(2, student_name_feildtext.getText());
		ps.setInt(3, Integer.parseInt(student_class_feildtext.getText()));
		ps.execute();
                JOptionPane.showMessageDialog(null, "Student added Sucessful!! Click refersh to see the changes");
                student_name_feildtext.setText("");
                student_class_feildtext.setText("");
                student_id_feildtext.setText("");
            }
            catch(Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,"Student not added sucessfully");
            }
        }        
    }//GEN-LAST:event_Student_addActionPerformed
    
    private void Student_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_updateActionPerformed
        // TODO add your handling code here:
         if ( student_name_feildtext.getText().isEmpty() || student_class_feildtext.getText().isEmpty() || student_id_feildtext.getText().isEmpty() ){
            JOptionPane.showMessageDialog(new JFrame(), "Choose a record from table to update", "Message" , JOptionPane.INFORMATION_MESSAGE);
        }else{
            try{
                String sql =  "Update student set name = ?, grade = ? where id = ?";
		PreparedStatement ps = dbconnect.librarycon.prepareStatement(sql);
                ps.setString(1, student_name_feildtext.getText());
		ps.setInt(2, Integer.parseInt(student_class_feildtext.getText()));
		ps.setInt(3, Integer.parseInt(student_id_feildtext.getText()));
		ps.execute();
                JOptionPane.showMessageDialog(null, "Update Sucessful!! Click refersh to see the changes");
                student_name_feildtext.setText("");
                student_class_feildtext.setText("");
                student_id_feildtext.setText("");
            }
            catch(Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Update not successfull!!!");
            }
        }
                
    }//GEN-LAST:event_Student_updateActionPerformed

    private void Student_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_deleteActionPerformed
        // TODO add your handling code here:
        if ( student_name_feildtext.getText().isEmpty() || student_class_feildtext.getText().isEmpty() || student_id_feildtext.getText().isEmpty() ){
            JOptionPane.showMessageDialog(new JFrame(), "Choose a record from table to delete", "Message" , JOptionPane.INFORMATION_MESSAGE);
        }else{
                           int result = JOptionPane.showConfirmDialog(student_jpanel_0,"Are you Sure? You want to Delete?", "Student record",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
             try{
                String sql = "Delete from student where id = ? ";
		PreparedStatement ps = dbconnect.librarycon.prepareStatement(sql);
		ps.setInt(1, Integer.parseInt(student_id_feildtext.getText()));
		ps.execute();
                JOptionPane.showMessageDialog(null, "Delete successfully!! Click refersh to see the changes");
                student_name_feildtext.setText("");
                student_class_feildtext.setText("");
                student_id_feildtext.setText("");
            }
            catch(Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Delete not sucessful!!!");
            }
            }
           
        }
    }//GEN-LAST:event_Student_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel model = (DefaultTableModel) Output_table.getModel();
            model.setRowCount(0);
            Statement st = dbconnect.librarycon.createStatement();
            String firstSql = "Select * from student order by id";
            ResultSet rs = st.executeQuery(firstSql);
            while (rs.next()) {
                String id = String.valueOf(rs.getInt("id"));
                String name = rs.getString("name");
                String grade  = String.valueOf(rs.getInt("grade"));

                String tbData[] = {id,name,grade};
                DefaultTableModel tblmodle = (DefaultTableModel)Output_table.getModel();

                tblmodle.addRow(tbData);
            }
            rs.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_refreshActionPerformed

    private void Output_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Output_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tb = (DefaultTableModel)Output_table.getModel();

        String tbid = tb.getValueAt(Output_table.getSelectedRow(), 0).toString();
        String tbname = tb.getValueAt(Output_table.getSelectedRow(), 1).toString();
        String tbgrade = tb.getValueAt(Output_table.getSelectedRow(), 2).toString();

        student_id_feildtext.setText(tbid);
        student_name_feildtext.setText(tbname);
        student_class_feildtext.setText(tbgrade);

    }//GEN-LAST:event_Output_tableMouseClicked

    private void student_id_feildtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_id_feildtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_id_feildtextActionPerformed
        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Studentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Studentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Studentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Studentform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Studentform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Goback;
    private javax.swing.JTable Output_table;
    private javax.swing.JButton Student_add;
    private javax.swing.JButton Student_delete;
    private javax.swing.JButton Student_update;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel student_class_feildname;
    private javax.swing.JTextField student_class_feildtext;
    private javax.swing.JLabel student_id_feildname;
    private javax.swing.JTextField student_id_feildtext;
    private javax.swing.JPanel student_jpanel_0;
    private javax.swing.JLabel student_name_feildname;
    private javax.swing.JTextField student_name_feildtext;
    private javax.swing.JPanel student_panel_1;
    private javax.swing.JPanel student_panel_2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
