/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package My_Forms;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author VAIBHAV
 */
public class Loginform extends javax.swing.JFrame {
    
    private static final long serialVersionUID = 1L;

    private JButton loginButton;
    
    private JTextField username;
    private JLabel userLabel;

  

    public Loginform() {
        initComponents();
      
        this.setLocationRelativeTo(null);
    }
    
   
    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        inventory_jpanel_0 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        login_username_field = new javax.swing.JLabel();
        login_username_fieldtext = new javax.swing.JTextField();
        login_password_field = new javax.swing.JLabel();
        inventory_login_button = new javax.swing.JButton();
        login_password_fieldtext = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);

        inventory_jpanel_0.setBackground(new java.awt.Color(255, 255, 255));

        title.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        title.setText("Digital Library managment ");

        login_username_field.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        login_username_field.setText("Enter username");

        login_username_fieldtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_username_fieldtextActionPerformed(evt);
            }
        });

        login_password_field.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        login_password_field.setText("Enter password");

        inventory_login_button.setBackground(new java.awt.Color(0, 0, 0));
        inventory_login_button.setForeground(java.awt.Color.white);
        inventory_login_button.setText("Login");
        inventory_login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inventory_login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventory_login_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inventory_jpanel_0Layout = new javax.swing.GroupLayout(inventory_jpanel_0);
        inventory_jpanel_0.setLayout(inventory_jpanel_0Layout);
        inventory_jpanel_0Layout.setHorizontalGroup(
            inventory_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inventory_jpanel_0Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(inventory_jpanel_0Layout.createSequentialGroup()
                .addGroup(inventory_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inventory_jpanel_0Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(inventory_login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inventory_jpanel_0Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(inventory_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_username_fieldtext, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                            .addComponent(login_password_fieldtext))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inventory_jpanel_0Layout.setVerticalGroup(
            inventory_jpanel_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inventory_jpanel_0Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(login_username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_username_fieldtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_password_field, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_password_fieldtext, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(inventory_login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventory_jpanel_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inventory_jpanel_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_username_fieldtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_username_fieldtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_username_fieldtextActionPerformed

    private void inventory_login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventory_login_buttonActionPerformed
        if (login_username_fieldtext.getText().equals("kamna")&& login_password_fieldtext.getText().equals("hello")){
            Dashboardform frm = new Dashboardform();
            frm.setVisible(true);
            this.setVisible(false);
        }
        else if(login_username_fieldtext.getText().equals("") && login_password_fieldtext.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter username and password");
        }
        else{
            JOptionPane.showMessageDialog(null,"Incorrect username and password");
        }

    }//GEN-LAST:event_inventory_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inventory_jpanel_0;
    private javax.swing.JButton inventory_login_button;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel login_password_field;
    private javax.swing.JTextField login_password_fieldtext;
    private javax.swing.JLabel login_username_field;
    private javax.swing.JTextField login_username_fieldtext;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
